# Generated by Django 4.1.1 on 2022-11-21 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_data_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_post',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 22, 48, 11, 499565, tzinfo=datetime.timezone.utc)),
        ),
    ]
