# Generated by Django 4.1.3 on 2022-12-03 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_autor_post_alter_post_categoria_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_post',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 22, 50, 6, 731874, tzinfo=datetime.timezone.utc), verbose_name='Data postada'),
        ),
    ]
