# Generated by Django 4.1.1 on 2022-11-21 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_comentario',
            field=models.DateField(default=datetime.datetime(2022, 11, 21, 22, 48, 11, 500247, tzinfo=datetime.timezone.utc)),
        ),
    ]
